### ISSUE TITLE
Upgrade to Java version 11 and remove sonarscanner warning

### ISSUE THREAD

**Issue by eye2web** [philips-software/docker-sonar-scanner#11]
I'm receiving te following WARN when running the docker container:

...
INFO: SonarScanner 4.4.0.2170
INFO: Java 1.8.0_265 Oracle Corporation (64-bit)
...
WARN: SonarScanner will require Java 11 to run starting in SonarQube 8.x
...

**Comment by eye2web** [comment]
More info: https://community.sonarsource.com/t/misleading-warning-in-sonarscanner-when-using-java-8/25848

**Comment by JeroenKnoops** [comment]
Has already been resolved in 4.4.0.2170

<img width="843" alt="Screenshot 2021-06-20 at 08 24 27" src="https://user-images.githubusercontent.com/10019/122665745-5921d600-d1a9-11eb-8803-a0d2686d3cb3.png">
